name: AngelInventories
version: 1.0-SNAPSHOT
main: sarah.angelinventories.AngelInventories
api-version: 1.16
authors: [Sarah]
description: Toggles inventories to allow multiple saved inventories

commands:
  ti:
    description: Used to toggle between multiple inventories
    usage: /ti num
    permission: AngelInventories.Inventories.2

  saveInventory:
    description: Used to save an inventory to the pre-set inventories
    usage: /saveinventory <inventory name>
    permission: AngelInventories.Admin

  setInventory:
    description: Used to set a player's inventory to one of the pre-set inventories, or set them back to their first inventory
    usage: /setinventory <player> <inventory name>
    permission: AngelInventories.Admin

  recoverInventory:
    description: Used to save an inventory to the pre-set inventories
    usage: /recoverinventory

  removeInventory:
    description: used to remove pre-set inventories
    usage: /removeinventory <inventory name>